//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PdpApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class DistType_LU
    {
        public string DISTTYPE { get; set; }
        public string DESCRIP { get; set; }
    }
}
