//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PdpApi
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PDPEntities : DbContext
    {
        public PDPEntities()
            : base("name=PDPEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Country_LU> Country_LU { get; set; }
        public virtual DbSet<PestCode_LU> PestCode_LU { get; set; }
        public virtual DbSet<SampleData> SampleDatas { get; set; }
        public virtual DbSet<Tolerance_LU> Tolerance_LU { get; set; }
        public virtual DbSet<ResultsData> ResultsDatas { get; set; }
        public virtual DbSet<telecom_order> telecom_order { get; set; }
        public virtual DbSet<Claim_LU> Claim_LU { get; set; }
        public virtual DbSet<Commod_History_LU> Commod_History_LU { get; set; }
        public virtual DbSet<Commod_LU> Commod_LU { get; set; }
        public virtual DbSet<CommType_LU> CommType_LU { get; set; }
        public virtual DbSet<ConfMethod_LU> ConfMethod_LU { get; set; }
        public virtual DbSet<ConUnit_LU> ConUnit_LU { get; set; }
        public virtual DbSet<Determin_LU> Determin_LU { get; set; }
        public virtual DbSet<DistType_LU> DistType_LU { get; set; }
        public virtual DbSet<Extract_LU> Extract_LU { get; set; }
        public virtual DbSet<Lab_LU> Lab_LU { get; set; }
        public virtual DbSet<Mean_LU> Mean_LU { get; set; }
        public virtual DbSet<Origin_LU> Origin_LU { get; set; }
        public virtual DbSet<Pest_History_LU> Pest_History_LU { get; set; }
        public virtual DbSet<Quantitate_LU> Quantitate_LU { get; set; }
        public virtual DbSet<State_LU> State_LU { get; set; }
        public virtual DbSet<TestClass_LU> TestClass_LU { get; set; }
        public virtual DbSet<Annotate_LU> Annotate_LU { get; set; }
    
        [DbFunction("PDPEntities", "get_pdp_result_tbl")]
        public virtual IQueryable<get_pdp_result_tbl_Result> get_pdp_result_tbl(Nullable<int> start_offset, Nullable<int> numb_rows)
        {
            var start_offsetParameter = start_offset.HasValue ?
                new ObjectParameter("start_offset", start_offset) :
                new ObjectParameter("start_offset", typeof(int));
    
            var numb_rowsParameter = numb_rows.HasValue ?
                new ObjectParameter("numb_rows", numb_rows) :
                new ObjectParameter("numb_rows", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.CreateQuery<get_pdp_result_tbl_Result>("[PDPEntities].[get_pdp_result_tbl](@start_offset, @numb_rows)", start_offsetParameter, numb_rowsParameter);
        }
    
        public virtual ObjectResult<spCommodityHistory_Result> spCommodityHistory()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spCommodityHistory_Result>("spCommodityHistory");
        }
    
        public virtual ObjectResult<spPesticideHistory_Result> spPesticideHistory()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spPesticideHistory_Result>("spPesticideHistory");
        }
    
        public virtual ObjectResult<spToleranceLevel_Result> spToleranceLevel()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spToleranceLevel_Result>("spToleranceLevel");
        }
    }
}
