//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PdpApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class ResultsData
    {
        public int SAMPLE_PK { get; set; }
        public string PESTCODE { get; set; }
        public short PDP_YEAR { get; set; }
        public string COMMOD { get; set; }
        public string COMMTYPE { get; set; }
        public string LAB { get; set; }
        public string TESTCLASS { get; set; }
        public Nullable<double> CONCEN { get; set; }
        public Nullable<double> LOD { get; set; }
        public string CONUNIT { get; set; }
        public string CONFMETHOD { get; set; }
        public string CONFMETHOD2 { get; set; }
        public string ANNOTATE { get; set; }
        public string QUANTITATE { get; set; }
        public string MEAN { get; set; }
        public string EXTRACT { get; set; }
        public string DETERMIN { get; set; }
    }
}
