//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PdpApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class SampleData
    {
        public int SAMPLE_PK { get; set; }
        public string STATE { get; set; }
        public string YEAR { get; set; }
        public string MONTH { get; set; }
        public string DAY { get; set; }
        public string SITE { get; set; }
        public string COMMOD { get; set; }
        public string SOURCE_ID { get; set; }
        public string VARIETY { get; set; }
        public string ORIGIN { get; set; }
        public string COUNTRY { get; set; }
        public string DISTTYPE { get; set; }
        public string COMMTYPE { get; set; }
        public string CLAIM { get; set; }
        public Nullable<short> QUANTITY { get; set; }
        public string GROWST { get; set; }
        public string PACKST { get; set; }
        public string DISTST { get; set; }
        public string ORIGST { get; set; }
    
        public virtual Country_LU Country_LU { get; set; }
    }
}
