//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PdpApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class telecom_order
    {
        public string Request_Number { get; set; }
        public Nullable<System.DateTime> Order_Date { get; set; }
        public Nullable<double> Fiscal_Year { get; set; }
        public string Submitter { get; set; }
        public string Location { get; set; }
        public string Program { get; set; }
        public string Branch { get; set; }
        public string Group { get; set; }
        public string Option { get; set; }
        public string Status { get; set; }
        public string Link { get; set; }
    }
}
