//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PdpApi
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tolerance_LU
    {
        public short PDP_YEAR { get; set; }
        public string PESTCODE { get; set; }
        public string COMMOD { get; set; }
        public string EPATOL { get; set; }
        public string TOLUNIT { get; set; }
    }
}
